[package]
name = "matrixmult"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "optimized"
path = "optimized.rs"

[[bin]]
name = "unoptimized"
path = "unoptimized.rs"

[dependencies]
rulinalg="0.4.2"